

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: healthist
      POSTGRES_DB: ad_management
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    environment:
      PORT: 8080
      POSTGRES_DSN: "host=db user=postgres password=healthist dbname=ad_management port=5432 sslmode=disable TimeZone=Asia/Shanghai"
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./advertisement-management-frontend
    restart: always
    ports:
      - "3000:80"  # 前端将通过nginx的80端口暴露为宿主机的3000端口
    depends_on:
      - backend

volumes:
  db_data: